### PR TITLE
Add hover text and explanation of red/blue text

### LINKED ISSUE #165: Online license list omits important limitations
Replaceable text, as presented in the online license list, does not accurately communicate what specific strings are permitted replacements, and may leave some users believing they are permitted to replace such text with *any* string of their choice.

This issue became apparent following a discussion here: https://github.com/spdx/license-list-XML/issues/1935

> I think what was most confusing to me as a new user was:
>
> - A link to explaining Matching Guidelines is not present on license text pages themselves (ie. the pages where the actual ~~colour-coded~~ replaceable text exists)
> - The Matching Guidelines do not make clear that "replaceable text" is specifically replaceable text (my assumption was that "replaceable" was being used in the broadest sense of the term)
>
> So from my initial usage, I would suggest presenting a similar note before any license text containing replaceable/omittable text, but ensuring it explains that ~~blue~~ certain text is omittable, and ~~red~~ certain text is replaceable with specific or generic strings. I think it would then be very helpful to link to the XML source following this notice, possibly explaining that such specific information can be found in the XML.

### PR DESCRIPTION
**Pull request by goneall**
Fixes #165

Here's a screenshot of the current implementation:

image

### CODE REVIEW

**Review by swinslow — APPROVED** [review]
LGTM, thank you @goneall!

**Comment by goneall** [comment]
Thanks for the review @swinslow 

I'll wait a couple more days to see if @recursivenomad has any comments before merging.

**Comment by recursivenomad** [comment]
Thanks for holding for my input, @goneall!  End of the year can be busy :)

I like it!

The technically curious side of me still feels that linking to a source for the specific text of each license ([such as the XML](https://github.com/spdx/LicenseListPublisher/issues/165#issuecomment-1861673084)) in a footnote might be useful just in case there are edge cases in the future where a user wishes to clarify something about the technical definition which is not captured on this page - but I acknowledge that that is future-proofing beyond the scope of the the original issue, and this PR certainly does resolve #165!

So if you're good with what's noted above, then it looks good to me to resolve 👍

**Comment by goneall** [comment]
Thanks @recursivenomad for the review.

> The technically curious side of me still feels that linking to a source for the specific text of each license (https://github.com/spdx/LicenseListPublisher/issues/165#issuecomment-1861673084) in a footnote might be useful just in case there are edge cases in the future where a user wishes to clarify something about the technical definition which is not captured on this page

I agree - it's just more technical work since it would involve changes to both the template and several Java files in the back end to pass through the template file (although one could kind of hack the file name based on the license name).

I'll go ahead and merge this.  If anyone is interested in creating a separate pull request to add the link to the XML file, that would be great.

**Comment by jlovejoy** [comment]
@goneall - this has the issue of the link going to a specific spot in the v2.3 spec... should we change to go to https://github.com/spdx/license-list-XML/blob/main/DOCS/license-matching-guidelines-and-templates.md (which may also have different numbering) before this next release?

**Comment by jlovejoy** [comment]
is there a hover-over for replaceable text implemented in this too??

**Comment by goneall** [comment]
> is there a hover-over for replaceable text implemented in this too??

Yes - this PR includes a hover-over for both

**Comment by goneall** [comment]
> is has the issue of the link going to a specific spot in the v2.3 spec... should we change to go to https://github.com/spdx/license-list-XML/blob/main/DOCS/license-matching-guidelines-and-templates.md (which may also have different numbering) before this next release?

It should be replaced, but I just did the release yesterday - so let's pick this up on the next release.

@swinslow - are you going to be making changes to the templates?  If so, do you mind adding this to your list?

**Pull request merged**
